### ISSUE TITLE
Missing mat file

### ISSUE THREAD

**Issue by StanlyHardy** [anhddo/DensityBasedDetection#1]
May i know where i can get mall_gt.mat file?

**Comment by anhddo** [comment]
Oh, it's about 2 year ^^!, I just look at the code base, it's look like a mess, don't know what I did in there. This [link](https://www.dropbox.com/s/9lft00vnp5e1xqc/luanvan.zip?dl=0) contained the file you need. This is all i can help, you're on your own now.
